import type * as acp from "@agentclientprotocol/sdk";
import { z } from "zod";

// --- Config option (subset of ACP SessionConfigOption we care about) ---

export interface ConfigOption {
  type: "select";
  id: string;
  name: string;
  category?: string | null;
  currentValue: string;
  options: Array<{ value: string; name: string }>;
}

// --- Shared interfaces used by both frontend and backend ---

/** Debug log entry produced by the frontend Logger or a future server log SSE bridge. */
export interface LogRecord {
  ts: number; // epoch ms
  level: "debug" | "info" | "warn" | "error";
  source: "client" | "server"; // v1 always 'client' (server-side bridge is future work)
  scope?: string; // e.g. "push" or "session.event"
  msg: string;
  args: string[]; // fields after safeStringify (cycle-safe, capped)
  sessionId?: string;
}

/** Logger interface shared by frontend (and a future backend implementation). */
export interface Logger {
  debug(msg: string, fields?: Record<string, unknown>): void;
  info(msg: string, fields?: Record<string, unknown>): void;
  warn(msg: string, fields?: Record<string, unknown>): void;
  error(msg: string, fields?: Record<string, unknown>): void;
  scope(name: string): Logger;
}

export interface PlanEntry {
  status: string;
  content: string;
}

/** rawInput payload attached to tool_call events. */
export type RawInput =
  | string
  | {
      path?: string;
      command?: string;
      old_str?: string | null;
      new_str?: string | null;
      file_text?: string | null;
    };

/** Session summary returned by GET /api/v1/sessions. */
export interface SessionSummary {
  id: string;
  cwd: string;
  title: string | null;
  model: string | null;
  mode: string | null;
  reasoning_effort: string | null;
  source: string;
  created_at: string;
  last_active_at: string;
}

/** Stored event row returned by GET /api/v1/sessions/:id/events. */
export interface StoredEvent {
  id: number;
  session_id: string;
  seq: number;
  type: string;
  data: string;
  created_at: string;
}

/** Pending permission request tracked in memory. */
export interface PendingPermission {
  requestId: string;
  sessionId: string;
  title: string;
  options: Array<{ optionId: string; label: string }>;
}

// --- Agent events (server → client) ---

export type AgentEvent =
  | { type: "connected"; agent: { name: string; version: string }; configOptions: ConfigOption[]; cancelTimeout?: number; recentPathsLimit?: number }
  | { type: "session_created"; sessionId: string; cwd?: string; title?: string | null; configOptions: ConfigOption[] }
  | { type: "config_option_update"; sessionId: string; configOptions: ConfigOption[] }
  | { type: "message_chunk"; sessionId: string; text: string }
  | { type: "thought_chunk"; sessionId: string; text: string }
  | { type: "tool_call"; sessionId: string; id: string; title: string; kind: string; rawInput?: RawInput }
  | { type: "tool_call_update"; sessionId: string; id: string; status: string; content?: unknown[] }
  | { type: "plan"; sessionId: string; entries: PlanEntry[] }
  | { type: "permission_request"; requestId: string; sessionId: string; title: string; toolCallId?: string | null; options: acp.PermissionOption[] }
  | { type: "prompt_done"; sessionId: string; stopReason: string }
  | { type: "session_deleted"; sessionId: string }
  | { type: "session_title_updated"; sessionId: string; title: string }
  | { type: "session_expired"; sessionId: string }
  | { type: "error"; message: string; sessionId?: string }
  // Events generated by the server (not the ACP agent)
  | { type: "user_message"; sessionId: string; text: string; images?: Array<{ path: string; mimeType: string }> }
  | { type: "permission_response"; sessionId?: string; requestId: string; optionName: string; denied: boolean }
  | { type: "config_set"; configId: string; value: string }
  | { type: "bash_command"; sessionId: string; command: string }
  | { type: "bash_output"; sessionId: string; text: string; stream: string }
  | { type: "bash_done"; sessionId: string; code: number | null; signal: string | null; error?: string }
  // Server lifecycle events (no sessionId)
  | { type: "agent_reloading" }
  | { type: "agent_reloading_failed"; error: string }
  // Per-session runtime state delta (broadcast to subscribed SSE clients)
  | { type: "state_patch"; sessionId: string; seq: number; patch: import("./session-state.ts").StatePatch }
  // Inbox messages (Stage B primitive)
  | { type: "message"; sessionId: string; message_id: string; from_ref: string; from_label: string | null; title: string; body: string; cwd: string | null }
  | { type: "message_created"; messageId: string }
  | { type: "message_consumed"; messageId: string; sessionId: string }
  | { type: "message_acked"; messageId: string }
  // Replay-only events (stored in DB, not sent live)
  | { type: "assistant_message"; sessionId?: string; text: string }
  | { type: "thinking"; sessionId?: string; text: string }
  | { type: "bash_result"; sessionId?: string; output: string; code: number | null; signal: string | null }
  | { type: "permission_response"; sessionId?: string; requestId: string; optionName: string; denied: boolean };

// --- Event interpreter types (used by public/js/event-interpreter.ts) ---

export interface ToolCallView {
  icon: string;
  title: string;
  detail?: string;
  detailPrefix?: string;
  showDiff: boolean;
}

export interface StatusIconResult {
  icon: string;
  className: string;
}

export interface PermissionClassification {
  cssClass: 'allow' | 'deny';
  apiAction: 'resolve' | 'deny';
}

export interface DiffLine {
  kind: 'file' | 'hunk' | 'add' | 'del' | 'context';
  text: string;
}

export interface PlanEntryView {
  symbol: string;
  content: string;
}

/** Content item from ACP tool_call_update events. */
export interface ToolContentItem {
  type?: string;
  terminalId?: string;
  content?: { text?: string } | Array<{ text?: string }>;
}

export interface NormalizedEventsResponse {
  events: StoredEvent[];
  streaming: { thinking: boolean; assistant: boolean };
  total?: number;
  hasMore?: boolean;
}

// --- Inbox message ingress (Stage B primitive) ---

const FROM_REF_ALLOWED = /^(cron|external):[A-Za-z0-9._\-+/]{1,120}$/;

export const MessageIngressSchema = z.object({
  from_ref: z.string().min(1).max(128).regex(FROM_REF_ALLOWED, {
    message:
      "from_ref must start with 'cron:' or 'external:' (reserved values and 'session:<id>' rejected in MVP)",
  }),
  from_label: z.string().max(64).optional(),
  to: z.union([z.literal("user"), z.string().regex(/^session:[^\s]+$/)]),
  deliver: z.enum(["silent", "inapp", "push"]).default("push"),
  dedup_key: z.string().max(128).optional(),
  title: z.string().min(1).max(256),
  body: z.string().max(64 * 1024),
  cwd: z.string().max(4096).optional(),
});

export type MessageIngressInput = z.infer<typeof MessageIngressSchema>;

export const MessageEventDataSchema = z.object({
  message_id: z.string().min(1),
  from_ref: z.string().min(1),
  from_label: z.string().nullish(),
  title: z.string(),
  body: z.string(),
  cwd: z.string().nullish(),
});

export type MessageEventData = z.infer<typeof MessageEventDataSchema>;

// --- Utility ---

export function errorMessage(err: unknown): string {
  if (err instanceof Error) return err.message;
  if (typeof err === "string") return err;
  try {
    return JSON.stringify(err);
  } catch {
    return String(err);
  }
}
