import { z } from "zod/v4";
import type * as acp from "@agentclientprotocol/sdk";

// --- Config option (subset of ACP SessionConfigOption we care about) ---

export interface ConfigOption {
  type: "select";
  id: string;
  name: string;
  category?: string | null;
  currentValue: string;
  options: Array<{ value: string; name: string }>;
}

// --- Shared interfaces used by both frontend and backend ---

export interface PlanEntry {
  status: string;
  content: string;
}

/** rawInput payload attached to tool_call events. */
export type RawInput =
  | string
  | {
      path?: string;
      command?: string;
      old_str?: string | null;
      new_str?: string | null;
      file_text?: string | null;
    };

/** Session summary returned by GET /api/sessions. */
export interface SessionSummary {
  id: string;
  cwd: string;
  title: string | null;
  model: string | null;
  mode: string | null;
  reasoning_effort: string | null;
  source: string;
  created_at: string;
  last_active_at: string;
}

/** Stored event row returned by GET /api/sessions/:id/events. */
export interface StoredEvent {
  id: number;
  session_id: string;
  seq: number;
  type: string;
  data: string;
  created_at: string;
}

/** Pending permission request tracked in memory. */
export interface PendingPermission {
  requestId: string;
  sessionId: string;
  title: string;
  options: Array<{ optionId: string; label: string }>;
}

// --- Agent events (server → client) ---

export type AgentEvent =
  | { type: "connected"; agent: { name: string; version: string }; configOptions: ConfigOption[]; cancelTimeout?: number }
  | { type: "session_created"; sessionId: string; cwd?: string; title?: string | null; configOptions: ConfigOption[]; busyKind?: "agent" | "bash" }
  | { type: "config_option_update"; sessionId: string; configOptions: ConfigOption[] }
  | { type: "message_chunk"; sessionId: string; text: string }
  | { type: "thought_chunk"; sessionId: string; text: string }
  | { type: "tool_call"; sessionId: string; id: string; title: string; kind: string; rawInput?: RawInput }
  | { type: "tool_call_update"; sessionId: string; id: string; status: string; content?: unknown[] }
  | { type: "plan"; sessionId: string; entries: PlanEntry[] }
  | { type: "permission_request"; requestId: string; sessionId: string; title: string; toolCallId?: string | null; options: acp.PermissionOption[] }
  | { type: "prompt_done"; sessionId: string; stopReason: string }
  | { type: "session_deleted"; sessionId: string }
  | { type: "session_title_updated"; sessionId: string; title: string }
  | { type: "session_expired"; sessionId: string }
  | { type: "error"; message: string; sessionId?: string }
  // Events generated by the server (not the ACP agent)
  | { type: "user_message"; sessionId: string; text: string; images?: Array<{ path: string; mimeType: string }> }
  | { type: "permission_resolved"; sessionId?: string; requestId: string; optionName: string; denied: boolean }
  | { type: "config_set"; configId: string; value: string }
  | { type: "bash_command"; sessionId: string; command: string }
  | { type: "bash_output"; sessionId: string; text: string; stream: string }
  | { type: "bash_done"; sessionId: string; code: number | null; signal: string | null; error?: string }
  // Replay-only events (stored in DB, not sent live over WS)
  | { type: "assistant_message"; sessionId?: string; text: string }
  | { type: "thinking"; sessionId?: string; text: string }
  | { type: "bash_result"; sessionId?: string; output: string; code: number | null; signal: string | null }
  | { type: "permission_response"; sessionId?: string; requestId: string; optionName: string; denied: boolean };

// --- Inbound WS messages (client → server) ---

const ImageSchema = z.object({
  data: z.string(),
  mimeType: z.string(),
  path: z.string().optional(),
});

export const WsMessageSchema = z.discriminatedUnion("type", [
  z.object({
    type: z.literal("new_session"),
    cwd: z.string().optional(),
    inheritFromSessionId: z.string().optional(),
  }),
  z.object({ type: z.literal("resume_session"), sessionId: z.string() }),
  z.object({ type: z.literal("delete_session"), sessionId: z.string() }),
  z.object({
    type: z.literal("prompt"),
    sessionId: z.string(),
    text: z.string(),
    images: z.array(ImageSchema).optional(),
  }),
  z.object({
    type: z.literal("permission_response"),
    sessionId: z.string().optional(),
    requestId: z.string(),
    optionId: z.string().optional(),
    optionName: z.string().optional(),
    denied: z.boolean().optional(),
  }),
  z.object({ type: z.literal("cancel"), sessionId: z.string() }),
  z.object({ type: z.literal("set_config_option"), sessionId: z.string(), configId: z.string(), value: z.string() }),
  z.object({ type: z.literal("bash_exec"), sessionId: z.string(), command: z.string() }),
  z.object({ type: z.literal("bash_cancel"), sessionId: z.string() }),
  z.object({ type: z.literal("visibility"), visible: z.boolean() }),
]);

export type WsMessage = z.infer<typeof WsMessageSchema>;

// --- Utility ---

export function errorMessage(err: unknown): string {
  if (err instanceof Error) return err.message;
  if (typeof err === "string") return err;
  try {
    return JSON.stringify(err);
  } catch {
    return String(err);
  }
}
